version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        VARIANT: 3
        USER_UID: 1000
        USER_GID: 1000

    # # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    env_file:
      - .env

    ports:
      - "${HOST_BACKEND_PORT}:${BACKEND_PORT}"

    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    # # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    ports:
      - "${HOST_FRONTEND_PORT}:80"

    env_file:
      - .env

  db:
    image: mysql:8.0.3
    restart: unless-stopped
    volumes:
      - mysql-prod:/var/lib/mysql
      - ./backend/db.sql:/docker-entrypoint-initdb.d/1.sql
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}"

volumes:
  mysql-prod:
