version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3
        # [Choice] Install Node.js
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    environment:
      MYSQL_HOST: "db"
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default

      VUE_APP_BACKEND_URL: http://localhost:8001

      CORS_ALLOWED_ORIGINS: "http://localhost:8080"

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mysql:8.0.3
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
      - ../backend/db.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - 3306
      - 8001:8001
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: default
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default


volumes:
  mysql:
